/**
 * Utilities for rendering email HTML templates.
 * Generates a light-themed, single-column email compatible with major email clients
 * (Apple Mail, Gmail, Outlook) with 100% inline styles.
 */

import { fmtDate } from "./calculations";

/**
 * Renders the HTML body for a Progress Report email.
 *
 * @param {Object} content - Structured content generated by Gemini
 * @param {string} [content.subject] - Email subject
 * @param {string} [content.highlights] - Top takeaways
 * @param {string} [content.trainingSummary] - Training load & volume analysis
 * @param {string} [content.bodyComposition] - Body comp notes (or null)
 * @param {string} [content.goalProgress] - Goal progression status
 * @param {string} [content.muscleBalance] - Muscle balance & symmetry notes
 * @param {string} [content.notableEvents] - PRs, plateaus, records
 * @param {string} [content.lookingAhead] - Forward-looking coaching advice
 * @param {string} periodType - 'weekly' | 'monthly'
 * @param {string} periodStart - YYYY-MM-DD
 * @param {string} periodEnd - YYYY-MM-DD
 * @returns {string} Fully styled HTML string
 */
export function renderReportEmailHtml(content, periodType = "weekly", periodStart = "", periodEnd = "") {
  const periodLabel = periodType === "monthly" ? "MONTHLY PROGRESS REPORT" : "WEEKLY PROGRESS REPORT";
  const dateRangeStr = periodStart && periodEnd
    ? `${fmtDate(periodStart)} – ${fmtDate(periodEnd)}`
    : "";

  const subjectText = content?.subject || `${periodLabel}: ${dateRangeStr}`;
  const highlightsText = content?.highlights || "";

  // Section definitions
  const sections = [
    { title: "Training Load &amp; Volume", icon: "🏋️‍♂️", text: content?.trainingSummary },
    { title: "Notable Events &amp; PRs", icon: "🏆", text: content?.notableEvents },
    { title: "Muscle Balance &amp; Symmetry", icon: "⚖️", text: content?.muscleBalance },
    { title: "Goal Progression", icon: "🎯", text: content?.goalProgress },
    { title: "Body Composition", icon: "📊", text: content?.bodyComposition },
    { title: "Looking Ahead", icon: "🔮", text: content?.lookingAhead },
  ];

  const renderedSections = sections
    .filter((s) => s.text && typeof s.text === "string" && s.text.trim().length > 0)
    .map(
      (s) => `
      <div style="margin-bottom: 24px; padding-bottom: 20px; border-bottom: 1px solid #E5E7EB;">
        <div style="font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #4B5563; margin-bottom: 8px;">
          ${s.icon} ${s.title}
        </div>
        <p style="margin: 0; font-size: 15px; line-height: 1.6; color: #1F2937;">
          ${s.text.replace(/\n/g, "<br />")}
        </p>
      </div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(subjectText)}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #F3F4F6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #111827; -webkit-font-smoothing: antialiased;">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #F3F4F6; padding: 24px 12px;">
    <tr>
      <td align="center">
        <!-- Main Email Container -->
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #E5E7EB; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          
          <!-- Header Banner -->
          <tr>
            <td style="padding: 28px 32px 20px 32px; background: linear-gradient(135deg, #15181D 0%, #1F242D 100%); border-bottom: 3px solid #F4B740;">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <span style="display: inline-block; font-size: 10px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: #F4B740; background-color: rgba(244, 183, 64, 0.15); padding: 4px 10px; border-radius: 9999px; margin-bottom: 8px;">
                      ${periodLabel}
                    </span>
                    ${dateRangeStr ? `<span style="font-size: 12px; color: #9CA3AF; margin-left: 8px;">${dateRangeStr}</span>` : ""}
                    <h1 style="margin: 8px 0 0 0; font-size: 22px; font-weight: 700; color: #FFFFFF; line-height: 1.3;">
                      ${escapeHtml(subjectText)}
                    </h1>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Main Content Body -->
          <tr>
            <td style="padding: 32px 32px 24px 32px;">

              <!-- Highlights Box -->
              ${highlightsText ? `
              <div style="background-color: #FEF9C3; border: 1px solid #FDE047; border-left: 4px solid #CA8A04; border-radius: 8px; padding: 16px 20px; margin-bottom: 28px;">
                <div style="font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #854D0E; margin-bottom: 6px;">
                  ✨ Key Takeaways
                </div>
                <p style="margin: 0; font-size: 15px; line-height: 1.5; color: #713F12; font-weight: 500;">
                  ${highlightsText.replace(/\n/g, "<br />")}
                </p>
              </div>
              ` : ""}

              ${renderedSections}

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 24px 32px; background-color: #F9FAFB; border-top: 1px solid #E5E7EB; text-align: center;">
              <p style="margin: 0 0 6px 0; font-size: 12px; color: #6B7280;">
                Generated automatically by your <strong>Workout Performance Dashboard</strong>.
              </p>
              <p style="margin: 0; font-size: 11px; color: #9CA3AF;">
                Keep up the consistent work · Every session counts.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function escapeHtml(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
